fa16-proj1/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  patch 'capture', to: 'pokemons#capture'
  patch 'damage', to:'pokemons#damage'
  get 'new_pokemon', to: 'pokemons#new'
  post 'create_pokemon', to: 'pokemons#create'
  devise_for :trainers
  resources :trainers

end

fa16-proj1/app/models/pokemon.rb
# == Schema Information
#
# Table name: pokemons
#
#  id         :integer          not null, primary key
#  name       :string
#  level      :integer
#  trainer_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Pokemon < ActiveRecord::Base
	belongs_to :trainer
	validates :name, presence: true, uniqueness: true
end

fa16-proj1/app/models/trainer.rb
# == Schema Information
#
# Table name: trainers
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#

class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pokemons
end

fa16-proj1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  protect_from_forgery with: :exception
end

fa16-proj1/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    trainerless_pokemon = Pokemon.where(trainer: nil)
    @pokemon = trainerless_pokemon.sample
  end

end

fa16-proj1/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

	def new
	end

	def create
		pokemon = Pokemon.new
		pokemon.name = params[:pokemon][:name]
		pokemon.level = 1
		pokemon.health = 100
		pokemon.trainer = current_trainer
		pokemon.save
		if pokemon.errors.present?
			flash[:error] = pokemon.errors.full_messages.to_sentence
			redirect_to new_pokemon_path
		else
			redirect_to trainer_path(current_trainer)
		end
	end

	def capture
		pokemon = Pokemon.find_by_id(params[:id])
		pokemon.trainer = current_trainer
		pokemon.save!
		redirect_to '/'
	end

	def damage
		pokemon = Pokemon.find_by_id(params[:id])
		pokemon.health -= 10
		if pokemon.health <= 0
			pokemon.destroy!
		else
			pokemon.save!
		end
		redirect_to trainer_path(pokemon.trainer_id)
	end
end

fa16-proj1/app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :authenticate_trainer!

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end

end

fa16-proj1/app/helpers/application_helper.rb
module ApplicationHelper
end

fa16-proj1/app/helpers/pokemon_helper.rb
module PokemonHelper
end

fa16-proj1/app/helpers/pokemons_helper.rb
module PokemonsHelper
end

fa16-proj1/app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>

<% end %>

fa16-proj1/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

fa16-proj1/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'PokePortal Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

fa16-proj1/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if trainer_signed_in? %>
  <li><%= link_to 'Edit Your Trainer', edit_trainer_registration_path %></li>
  <li><%= link_to 'Log Out', destroy_trainer_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_trainer_session_path %></li>
  <li><%= link_to 'Join PokePortal', new_trainer_registration_path %></li>
<% end %>

fa16-proj1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsdecal Proj1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Railsdecal Proj1" %>">
    <%= stylesheet_link_tag 'default', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

fa16-proj1/app/views/pokemons/new.html.erb
<%= simple_form_for Pokemon.new ,  url: create_pokemon_path do |f| %>
	<%= f.input :name %>
	<%= f.button :submit %>
<% end %>

fa16-proj1/app/views/trainers/_trainer.html.erb
<td><%= link_to trainer.name, trainer %></td>
<td><%= link_to trainer.email, trainer %></td>

fa16-proj1/app/views/trainers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Trainers</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @trainers.each do |trainer| %>
            <tr>
              <%= render trainer %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

fa16-proj1/app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>
<% @trainer.pokemons.each do |p| %>
	<div> Name: <%= p.name %> </div>
	<div> Level: <%= p.level %> </div>
	<div> Health: <%= p.health %></div>
	<%= button_to "Damage!", damage_path(id: p), :class => "button medium", :method => :patch %>
<% end %>
<% if @trainer == current_trainer %>
	<%= link_to 'Create pokemon', new_pokemon_path %>
<% end %>